### ISSUE TITLE
大佬 你这个网站是用静态生成器生成的么？

### ISSUE THREAD

**Issue by aixiaoo** [geekxh/hello-algorithm#52]
大佬 你这个网站用的什么静态生成器？

**Comment by hexi007** [comment]
不好意思，你可能弄错了，这不是我的项目
---原始邮件---
发件人:&quot;aixiao&quot;<notifications@github.com&gt;
发送时间:2020年11月29日 星期日 下午11:7
收件人:&quot;geekxh/hello-algorithm&quot;<hello-algorithm@noreply.github.com&gt;
抄送:&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;
主题:[geekxh/hello-algorithm] 大佬 你这个网站是用静态生成器生成的么？ (#52)



大佬&nbsp;你这个网站用的什么静态生成器？

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;are&nbsp;subscribed&nbsp;to&nbsp;this&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by aixiaoo** [comment]
https://www.geekxh.com/
我是看到这个网站找过来的
我看着很漂亮  所以想知道用的什么生成器
我看着像vuepress+这个主题[vuepress-theme-reco](https://github.com/vuepress-reco/vuepress-theme-reco)
这个是[主题文档](https://vuepress-theme-reco.recoluan.com/) 看着非常像

**Comment by aixiaoo** [comment]
> 不好意思，你可能弄错了，这不是我的项目 ---原始邮件--- 发件人:"aixiao"<notifications@github.com> 发送时间:2020年11月29日 星期日 下午11:7 收件人:"geekxh/hello-algorithm"<hello-algorithm@noreply.github.com> 抄送:"Subscribed"<subscribed@noreply.github.com> 主题:[geekxh/hello-algorithm] 大佬 你这个网站是用静态生成器生成的么？ (#52) 大佬 你这个网站用的什么静态生成器？ — You are receiving this because you are subscribed to this thread. Reply to this email directly,view it on GitHub, orunsubscribe.

大佬  你好像不在这个项目的贡献者里  我也不清楚为什么issues会提到你那里

**Comment by huangpng** [comment]
你好



---原始邮件---
发件人: "aixiao"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 晚上11:48
收件人: "geekxh/hello-algorithm"<hello-algorithm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [geekxh/hello-algorithm] 大佬 你这个网站是用静态生成器生成的么？ (#52)




  
不好意思，你可能弄错了，这不是我的项目 ---原始邮件--- 发件人:"aixiao"notifications@github.com 发送时间:2020年11月29日 星期日 下午11:7 收件人:"geekxh/hello-algorithm"hello-algorithm@noreply.github.com 抄送:"Subscribed"subscribed@noreply.github.com 主题:[geekxh/hello-algorithm] 大佬 你这个网站是用静态生成器生成的么？ (#52) 大佬&nbsp;你这个网站用的什么静态生成器？ — You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;are&nbsp;subscribed&nbsp;to&nbsp;this&nbsp;thread. Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
  
大佬  你好像不在这个项目的贡献者里  我也不清楚为什么issues会提到你那里

**Comment by hexi007** [comment]
你可以点进我的github主页进去看看，是没有这个项目的，我只是给它标了个star
---原始邮件---
发件人:&quot;aixiao&quot;<notifications@github.com&gt;
发送时间:2020年11月29日 星期日 下午11:41
收件人:&quot;geekxh/hello-algorithm&quot;<hello-algorithm@noreply.github.com&gt;
抄送:&quot;hexi007&quot;<2777125829@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;
主题:Re: [geekxh/hello-algorithm] 大佬 你这个网站是用静态生成器生成的么？ (#52)



https://www.geekxh.com/
我是看到这个网站找过来的
我看着很漂亮&nbsp;&nbsp;所以想知道用的什么生成器
我看着像vuepress+这个主题vuepress-theme-reco
这个是主题文档看着非常像

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by huangpng** [comment]
你好，你发的邮件地址好像找的并不是我！
Hello, the email address you sent seems not to me!

---原始邮件---
发件人: "aixiao"<notifications@github.com&gt;
发送时间: 2020年11月29日(周日) 晚上11:41
收件人: "geekxh/hello-algorithm"<hello-algorithm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [geekxh/hello-algorithm] 大佬 你这个网站是用静态生成器生成的么？ (#52)




 
https://www.geekxh.com/
 我是看到这个网站找过来的
 我看着很漂亮  所以想知道用的什么生成器
 我看着像vuepress+这个主题vuepress-theme-reco
 这个是主题文档 看着非常像
